### ISSUE TITLE
Unknown column "pips_me" in output file

### ISSUE THREAD

**Issue by svenkatesh25** [mancusolab/ma-focus#23]
Hello, I've been performing some MAFOCUS analysis and I noticed that a column in the output file was not described in the wiki. I assume the column "pips_me" is the meta analysis PIP, but can you confirm? Thank you!

**Comment by zeyunlu** [comment]
@svenkatesh25  Hi, thanks for reaching out and I'm sorry about that I didn't see it until now. 

I'm sorry about the poor documentation, the pips_me is the MA-FOCUS pip, not the meta-analyzed one. We will update our documentation accordingly.
