### ISSUE TITLE
[ERROR] Could not determine N column.

### ISSUE THREAD

**Issue by elnetwas** [mancusolab/ma-focus#25]
Hello, I'm trying to use FOCUS for colocalization. When I run 'focus munge' on some GWAS statistics, I get the error [ERROR] Could not determine N column. My GWAS data does not include the term N. The wiki page states that only CHR, SNP, BP, A1 (effect allele), A2, BETA (or OR), and P are needed to produce a munged GWAS data file. Is there any way to calculate N?

Thank you!!!!

**Comment by zeyunlu** [comment]
Hello, sorry about the late reply as I don't normally check this issue thread.

I don't think N really matters here, you can create a column with name N and "place-holder" value here to pass the error message. Alternatively, if you need to estimate N for the future use, for large GWAS data, 1/(SE^2) can be a good approximation for the sample size.
