### ISSUE TITLE
Why FOCUS does not output TWAS p values?

### ISSUE THREAD

**Issue by liqingbioinfo** [mancusolab/ma-focus#29]
Dear authors
     
       I ran through the Focus using code and data indicated on https://github.com/mancusolab/ma-focus/wiki/FOCUS:-Fine-mapping-TWAS-associations-in-a-single-ancestry-group. The output file contains the following header line, which does not contains TWAS pvalues. Can you please let me know if I missed something to generate them? Could I use twas_z_pop1 to derive TWAS P values?

`focus finemap ./EA_WBC.Chen.2020/EA_WBC_new_munged_chr22.tsv.gz ./1000GP3_multiPop_allelesAligned/EUR/1000G.EUR.QC.allelesAligned.22 ./ea_fusion_genoa.db --chr 22 --locations 38:EUR --out ./focus_result`

The header of my ouptut file: 
block	ens_gene_id	ens_tx_id	mol_name	tissue	ref_name	type	chrom	tx_start	tx_stop	block_genes  trait	inference_pop1	inter_z_pop1	cv.R2_pop1	cv.R2.pval_pop1	ldregion_pop1	twas_z_pop1	pips_pop1	in_cred_set_pop1

     
Thank you 
Qing

**Comment by zeyunlu** [comment]
Hi Qing,

Thank you for using our software, and I apologize for the delayed response—I only just saw your message.

You can convert TWAS Z-scores to P-values using the following formula in R:

`2 * pnorm(abs(Z), lower.tail = FALSE)`

or the equivalent function in Python. We didn’t include TWAS P-values in the output to save space, as P-values and Z-scores are somewhat redundant.

Please feel free to reach out if you have any additional questions or need further clarification.

Thank you!

Best regards,
Zeyun
