### ISSUE TITLE
[finemap] The plot option not worked for the deprecation in numpy

### ISSUE THREAD

**Issue by s-i-immunol** [mancusolab/ma-focus#30]
Hello,
I truly appreciate your development of the very useful software ma-focus.

I encountered the following error message while running finemap with the --plot option:
 
[2024-11-23 11:43:10 - ERROR] module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    

I am using ma-focus in a Conda environment on Ubuntu 18.04 (conda create -n ma-focus python=3.8).
This issue seems to be related to changes introduced in recent versions of NumPy.

Could you please look into this and consider addressing the problem?

Thank you!

Sincerely,
Sho

**Comment by zeyunlu** [comment]
Hi Sho,

Thank you so much for using our software.

It seems np.bool was deprecated but still available in numpy versions prior to 1.24. You can edit the setup.py file by adding numpy==1.23.0, and re-install the software.

Please let me know if you have any questions!

Best,
Zeyun
