### ISSUE TITLE
Inconsistent FUSION db import

### ISSUE THREAD

**Issue by KangchengHou** [mancusolab/ma-focus#9]
Hi Zeyun and Nick,

Thanks for developing this which is super useful. I want to note on the inconsistency between

https://github.com/mancusolab/ma-focus/blob/fa8153d742327a3469436d529af9ce4a24a1e522/pyfocus/models/convert.py#L84

and

https://github.com/bogdanlab/focus/blob/2c5d04d2ce256a83b38c75eb0fb59885005ab5c6/pyfocus/models/convert.py#L83

http://gusevlab.org/projects/fusion/#gtex-v8-multi-tissue-expression works with old version but not new version.

A fix could be to first detect the header columns of the FUSION db.

I also wonder if there is a GTEx v8 focus.db?

**Comment by xNielx** [comment]
I'm also interested in a GTEx v8 focus.db

**Comment by BeataLILILI** [comment]
> I'm also interested in a GTEx v8 focus.db. I have GTEx_v8.db files for all the separate tissues, but have no idea how to combine them into one file to be used for FOCUS.

Hi, I am also trying to create GTEx v8 focus.db but I am struggling to create .db files for individual companies, I always get an error 502 Server Error: bad gateway for url: http://mygene.info/v3/query/, have you encountered this sort of issue?

**Comment by zeyunlu** [comment]
Sorry, I don't think we have encountered this issue. I think one workaround is to check our example db and try to follow the exact format we had in the example db.

**Comment by BeataLILILI** [comment]
> 抱歉，我认为我们没有遇到过这个问题。我认为一个解决方法是检查我们的示例数据库并尝试遵循示例数据库中的确切格式。

Thank you for your reply, I have tried to run it with the sample data and sample code, but I still get this error.
             FOCUS v0.803             
===================================
focus import
        ./NTR.BLOOD.RNAARR.pos
        fusion
        --tissue blood
        --name NTR
        --assay array
        --output fusion

Starting log...
[2024-07-30 08:42:10 - INFO] Preparing weight database
[2024-07-30 08:42:11 - INFO] Starting import from FUSION database ./NTR.BLOOD.RNAARR.pos
[2024-07-30 08:42:11 - INFO] Querying mygene servers for gene annotations
[2024-07-30 08:43:12 - ERROR] 502 Server Error: Bad Gateway for url: http://mygene.info/v3/query/
[2024-07-30 08:43:12 - INFO] Finished importing prediction models

**Comment by zeyunlu** [comment]
@quattro any thoughts?

**Comment by BeataLILILI** [comment]
> @quattro有什么想法吗？

Sorry, and I am now able to run the data in WSL on my local computer. It is possible that the previous error was caused by the network between the two servers being of a poor quality, which made it difficult to access http://mygene.info/v3/query/. However, everything is now functioning correctly, with the exception of the alerts of "Unable to match ENSG00000205485.13 to Ensembl ID. Using ID for symbol". I extend my gratitude for your efforts.

**Comment by rodrigoduarte88** [comment]
> 024-07-30 08:42:10 - INFO] Preparing weight database
> [2024-07-30 08:42:11 - INFO] Starting import from FUSION database ./NTR.BLOOD.RNAARR.pos
> [2024-07-30 08:42:11 - INFO] Querying mygene servers for gene annotations
> [2024-07-30 08:43:12 - ERROR] 502 Server Error: Bad Gateway for url: http://mygene.info/v3/query/
> [2024-07-30 08:43:12 - INFO] Finished importing prediction models

I came across this error in the past, and the error disappeared after a few days. The mygene.info website is not super stable I believe.




> I'm also interested in a GTEx v8 focus.db. I have GTEx_v8.db files for all the separate tissues, but have no idea how to combine them into one file to be used for FOCUS.

To combine into a single weights file, you just keep specifying the same .db file for `focus import`. The standard behaviour of focus import is to "add" features into the database, and not to overwrite the file.
